- hosts: wbservers
  vars:
    file_name: test
  tasks:
    - name: retrive the data of {{file_name}}
      state:
         path: "/tmp/{{file_name}}"
      register: file

    - debug:
        msg: "the file exists"
      when: file.stat.exits == true
