- hosts: dbservers
  vars:
    file_name: test1
  tasks:
    - name: creat file
      copy: src=/tmp/{{file_name}} dest=/tmp/{{file_name}}
    - name: retrive the data of the {{file_name}}
      stat:
        path: "/tmp/{{file_name}}"
      register: file

    - debug:
         var: file
#        msg: "the file exists"
#     when: file.stat.exits == true
~
